### ISSUE TITLE
Todo-List 1

### ISSUE THREAD

**Issue by kamapu** [kamapu/kamapu.github.io#4]
Some issues that are priority in this page

- [x] Add icons in navbar
- [x] Draft the page footer
- [ ] Design automatic workflow for updating databases
- [ ] Include database overviews as posts (automatic update)
- [ ] Include former workshops as posts
- [ ] Design list of keywords (metadata)
- [ ] Expand blogposts

**Comment by kamapu** [comment]
Icons added in https://github.com/kamapu/kamapu.github.io/commit/8d45f1d19fcb2af491f60fa7175b69f4be6b88a7

**Comment by kamapu** [comment]
Page footer added in https://github.com/kamapu/kamapu.github.io/commit/8ba42c8b2d4a331ec204a22c727868b47a234b9d
